// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebService.DataAccess;

namespace WebService.Migrations
{
    [DbContext(typeof(WallsMonitorDbContext))]
    [Migration("20190520163955_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebService.DataAccess.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime");

                    b.Property<int>("ExtensionServiceJobsId");

                    b.Property<string>("ExtensionServiceName");

                    b.Property<string>("ExtensionType");

                    b.Property<string>("FinalStatus");

                    b.Property<string>("JobState");

                    b.Property<string>("JobType");

                    b.Property<string>("LibraryName");

                    b.Property<string>("Messages");

                    b.Property<Guid>("OperationId");

                    b.Property<DateTime>("QueueTime");

                    b.Property<int>("Retries");

                    b.Property<DateTime>("StartTime");

                    b.Property<DateTime>("StateLastChangedTime");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("WebService.DataAccess.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassName");

                    b.Property<string>("LogContent");

                    b.Property<string>("LogMessage");

                    b.Property<string>("LogSource");

                    b.Property<string>("MachineName");

                    b.Property<string>("MethodName");

                    b.Property<string>("ThreadId");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("WebService.DataAccess.Models.Metrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MachineName");

                    b.Property<string>("Memory");

                    b.Property<string>("PhysicalDisk");

                    b.Property<string>("Processor");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.ToTable("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
